# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"
env:
  - PYTHON_VM=cpython
matrix:
  include:
    - python: 2.7
      env: PYTHON_VM=ironpython
    - python: pypy
      env: PYTHON_VM=pypy
  exclude:
    - python: pypy
      env: PYTHON_VM=cpython


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test
